blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("sitio.urls")),
    path('sitio/', include("sitio.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitio/urls.py
from django.urls import path
from . import views

app_name = "sitio"
urlpatterns = [
    path('', views.index, name="index"),
    path('acerca_de', views.acerca_de, name="acerca_de"),
    path('carrito_vista', views.carrito_vista, name="carrito_vista"),    
    path('carrito_agregar/<int:producto_id>', views.carrito_agregar, name="carrito_agregar"),      
    path('carrito_eliminar/<int:producto_id>', views.carrito_eliminar, name="carrito_eliminar"),      
    path('carrito_vaciar', views.carrito_vaciar, name="carrito_vaciar"),
    path('registrarse', views.registrarse, name="registrarse"),
    path('filtro_busqueda', views.filtro_busqueda, name="filtro_busqueda"),
    path('filtro_categorias/<int:categoria_id>', views.filtro_categorias, name="filtro_categorias"),    
    path('producto_vista/<int:producto_id>', views.producto_vista, name="producto_vista"),
    path('producto_alta', views.producto_alta, name="producto_alta"),
    path('producto_edicion/<int:producto_id>', views.producto_edicion, name="producto_edicion"),
    path('producto_eliminacion/<int:producto_id>', views.producto_eliminacion, name="producto_eliminacion"),

]

sitio/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Categoria(models.Model):
    descripcion = models.CharField(max_length=64, null=False)
    def __str__(self):
        return f"{self.descripcion}"

class Producto(models.Model):
    titulo = models.CharField(max_length=250, null=False)
    imagen = models.FileField(upload_to='imagenes/')
    descripcion = models.CharField(max_length=2000, null=False)
    precio = models.FloatField()
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, related_name="producto_categoria")

class Carrito(models.Model): 
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name="carrito_usuario")
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, related_name="carrito_producto") 
    

sitio/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Producto

class FormProducto(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ('titulo', 'categoria', 'descripcion', 'precio', 'imagen')
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'pub_titulo'}),
            'descripcion': forms.Textarea(attrs={'class': 'pub_descripcion'}),
            'imagen': forms.FileInput(attrs={'name':'imagen_adjunta', 'class': 'pub_imagen'}),
            'precio': forms.TextInput(attrs={'class': 'pub_precio'}),
        }


class RegistroForm(UserCreationForm):
    email = forms.EmailField(
        label='Email', widget=forms.TextInput(attrs={'class': 'email'}), max_length=254, required=True, help_text='')
    username = forms.CharField(
        label='Usuario', widget=forms.TextInput(attrs={'class': 'usuario'}), max_length=150, required=True, help_text='')
    password1 = forms.CharField(
        label='Password', widget=forms.PasswordInput(), max_length=30, required=True, help_text='')
    password2 = forms.CharField(
        label='Repetir Password', widget=forms.PasswordInput(), max_length=30, required=True, help_text='')
    class Meta:
        model = User
        fields = ('email', 'username', 'password1', 'password2', )

sitio/views.py
from django.contrib.auth.models import User
from django.db.models.query import QuerySet
from django.db.models import Q
from django.http.response import HttpResponseRedirect
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from .forms import *
from .models import Categoria, Producto, Carrito
from django.utils import timezone
from django.contrib.auth.decorators import login_required
# from django.contrib.auth.decorators import permission_required

# Create your views here.

def index(request):
    return render(request,"blog/index.html", {
        "lista_productos": Producto.objects.all().order_by('-id')[:10],
        "lista_categorias": Categoria.objects.all(),
    })

def registrarse(request):
    if request.method == 'POST':
        form = RegistroForm(request.POST)
        if form.is_valid():
            form.save()          
            return HttpResponseRedirect(reverse('login'))
    else:
        form = RegistroForm()
    return render(request, 'registration/registro.html', {
        'form': form
        })    

def filtro_busqueda(request):
    queryset = request.GET['buscador']
    if queryset:
        productos = Producto.objects.filter(
            Q(titulo__icontains = queryset) | 
            Q(descripcion__icontains = queryset) 
        ).distinct()
    return render(request,"blog/busqueda.html", {
        "lista_productos": productos,
        "lista_categorias": Categoria.objects.all(),
    })

def filtro_categorias(request, categoria_id):
    una_categoria = get_object_or_404(Categoria, id=categoria_id)
    queryset = Producto.objects.all()
    queryset = queryset.filter(categoria=una_categoria)
    return render(request,"blog/busqueda.html", {
        "lista_productos": queryset,
        "lista_categorias": Categoria.objects.all(),
        "categoria_seleccionada": una_categoria,
    })    

def producto_vista(request, producto_id):
    un_producto = get_object_or_404(Producto, id=producto_id)
    return render(request, "blog/producto_vista.html", {
        "producto": un_producto,
        "lista_categorias": Categoria.objects.all(),
    })

def producto_alta(request):
    if request.method == "POST":
        user = User.objects.get(username=request.user)
        form = FormProducto(request.POST, request.FILES, instance=Producto(imagen=request.FILES['imagen']))      
        if form.is_valid():
            form.save()
            return redirect("sitio:index")          
    else:
        form = FormProducto(initial={})
        return render(request, "blog/producto_nuevo.html", {
            "form": form,
            "lista_categorias": Categoria.objects.all(),
        })


def producto_edicion(request, producto_id):
    un_producto = get_object_or_404(Producto, id=producto_id)
    if request.method == "POST":  
        user = User.objects.get(username=request.user)   
        form = FormProducto(data=request.POST, files=request.FILES, instance=un_producto)
        if form.is_valid():
            form.save()
            return redirect("sitio:index")
    else:
        form = FormProducto(instance = un_producto)
        return render(request, 'blog/producto_edicion.html', {
            "producto": un_producto,
            "form": form,
            "lista_categorias": Categoria.objects.all(),
        })

def producto_eliminacion(request, producto_id):
    un_producto = get_object_or_404(Producto, id=producto_id)
    un_producto.delete()
    return redirect("sitio:index")

def acerca_de(request):
    return render(request, "blog/acerca_de.html", {
        "lista_categorias": Categoria.objects.all(),
    })

def carrito_vista(request):
    return render(request, "blog/carrito_vista.html", {
        "lista_carrito": Carrito.objects.filter(usuario=request.user.id).select_related("producto","usuario"),
        "lista_categorias": Categoria.objects.all(),
    })
 
def carrito_agregar(request, producto_id):
    carrito = Carrito.objects.create(producto_id=producto_id, usuario_id=request.user.id)
    carrito.save
    return redirect("sitio:index")

def carrito_eliminar(request, producto_id):
    carrito = get_object_or_404(Carrito, producto_id=producto_id, usuario_id=request.user.id)
    carrito.delete()
    return render(request, "blog/carrito_vista.html", {
        "lista_carrito": Carrito.objects.filter(usuario=request.user.id).select_related("producto","usuario"),
        "lista_categorias": Categoria.objects.all(),
    })

def carrito_vaciar(request):
    Carrito.objects.filter(usuario=request.user.id).all().delete()
    return render(request, "blog/carrito_vista.html", {
        "lista_carrito": Carrito.objects.filter(usuario=request.user.id).select_related("producto","usuario"),
        "lista_categorias": Categoria.objects.all(),
    })

sitio/templates/blog/acerca_de.html
{% extends "blog/layout.html" %}
{% block content %}

<br>
<h4>Acerca de nosotros</h4>
<br>
<p>Garantizar las propiedades únicas de la naturaleza.

    Los procesos de investigación, desarrollo, elección de materia prima y control exhaustivo de la producción reúnen a un experimentado equipo de profesionales de distintas especialidades (médicos, nutricionistas, ingenieros químicos, bromatólogos), para garantizar en cada producto las propiedades únicas de la naturaleza y la máxima calidad de elaboración acorde a estándares internacionales.
    
    La selección, recepción y manipulación de materia prima responde a estrictas normas operativas. Un sinnúmero de investigaciones y ensayos respaldan el desarrollo de todo producto nuevo, con sucesivos ajustes en la formulación hasta alcanzar los parámetros deseados. Cada línea de productos Grandiet cuenta con la aprobación de los organismos oficiales pertinentes y es sometida a procesos de mejora y prueba continua, a fin de asegurar y potenciar en todo momento sus cualidades naturales propias y la mejor calidad del mercado.</p>

    <br>
    <a href="{% url 'sitio:index'%}" role="button"> Volver </a>
{% endblock %}

sitio/templates/blog/busqueda.html
{% extends "blog/layout.html" %}
{% block content %}
<br>
<h4>Resultado de búsqueda</h4>
<br>

<div class="list-group">
    {% for un_producto in lista_productos %}  
        {% if user.is_staff %}   
            <a href="{% url 'sitio:producto_edicion' un_producto.id %}" class="list-group-item list-group-item-action" aria-current="true"> 
        {% else %}  
            <a href="{% url 'sitio:producto_vista' un_producto.id %}" class="list-group-item list-group-item-action" aria-current="true"> 
        {% endif %}   
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{un_producto.titulo}}</h5>
                </div>
                <p class="mb-1">{{un_producto.descripcion}}</p>
            </a>
    {% empty %}
        <li  class="list-group-item">No hay productos en esta categoría.</li>
    {% endfor %}
  </div>

<br>
<br>
{% endblock %}

sitio/templates/blog/carrito_vista.html
{% extends "blog/layout.html" %}
{% block content %}
<br>
<h4>Carrito</h4>
  
<br>

<div class="table-responsive">
    <b>Usuario: {{ user.get_username }}</b> 
    <br><br>
    <table class="table align-middle">
      <tbody>
        {% for un_producto in lista_carrito %}
        <tr>
          <td class="align-top"><h6>{{un_producto.producto.id}}.{{un_producto.producto.titulo}}</h6></td>
          <td class="align-top"><p>{{un_producto.producto.descripcion}}</p></td>
          <td class="align-top"><b>${{un_producto.producto.precio}}</b></td>
          <td class="align-top"><a class="btn btn-primary btn-sm" href="{% url 'sitio:carrito_eliminar' un_producto.producto.id %}" role="button">Eliminar</a></td>
        </tr>
        {% empty %}
            <li>No hay productos en tu carrito..</li>
        {% endfor %}
      </tbody>
    </table>
  </div>

<div class="d-grid gap-2 d-md-flex justify-content-md-end">
  {% if lista_carrito.count > 0 %}    
    <a class="btn btn-primary btn-sm" href="{% url 'sitio:carrito_vaciar' %}" role="button">Vaciar carrito</a></td>
    <a class="btn btn-primary btn-sm" href="" role="button">Finalizar compra</a></td>
  {% endif %}
  </div>

<br>
{% endblock %}

sitio/templates/blog/index.html
{% extends "blog/layout.html" %}
{% block content %}
<br>
<h4>Productos</h4>
    <br>

    <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for un_producto in lista_productos %}
        {% if forloop.counter < 4 %}
        <div class="col">
            <div class="card h-80 text-center">                 
                <div class="card-body">
                    <h5 class="card-title" >{{un_producto.titulo}}</h5>    
                    <img src="{{ media_url  }}{{ un_producto.imagen.url }}" class="card-img-top" alt="producto" width="100" height="240">    
                </div>
                <div class="card-footer">
                    {% if user.is_staff %}    
                        <a class="btn btn-primary btn-sm" href="{% url 'sitio:producto_edicion' un_producto.id %}" role="button"> Ver </a>  
                    {% else %}  
                        <a class="btn btn-primary btn-sm" href="{% url 'sitio:producto_vista' un_producto.id %}" role="button"> Ver </a>
                    {% endif %}   
                </div>
            </div>
        </div>      
        {% endif %}
    {% endfor %}
    </div>
    <br>
    <h5>Más Productos</h5>
    <br>
    <div class="list-group">
        {% for un_producto in lista_productos %}
            {% if forloop.counter > 3 %}   
                {% if user.is_staff %}   
                    <a href="{% url 'sitio:producto_edicion' un_producto.id %}" class="list-group-item list-group-item-action" aria-current="true"> 
                {% else %}  
                    <a href="{% url 'sitio:producto_vista' un_producto.id %}" class="list-group-item list-group-item-action" aria-current="true"> 
                {% endif %}   
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">{{un_producto.titulo}}</h5>
                        </div>
                        <p class="mb-1">{{un_producto.descripcion}}</p>
                    </a>
            {% endif %}
        {% empty %}
            <li  class="list-group-item">No hay productos en esta categoría.</li>
        {% endfor %}
      </div>
     
    <br>
    <br>
{% endblock %}

sitio/templates/blog/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'estilos.css' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="{% static 'scripts.js' %}"></script>     
        <title>Venta de hiervas medicinales</title>
        
    </head>
    <body>     
        <div class="container">

            <!-- Cabecera--> 
            <header id="cabecera">                
                <div id="bloque_login">
                    {% if user.is_authenticated %}
                        Bienvenido {{ user.get_username }}! <a role="button" class="btn btn-outline-warning btn-sm" href="{% url 'logout'%}?next={{request.path}}">Salir</a>
                        {% if not user.is_staff %}
                        <a role="button" class="btn btn-outline-success btn-sm" href="{% url 'sitio:carrito_vista' %}">Carrito</a>
                        {% endif %}    
                    {% else %}                  
                        <a role="button" class="btn btn-outline-success btn-sm" href="{% url 'login'%}?next={{request.path}}">Acceder</a>
                        <a role="button" class="btn btn-outline-success btn-sm" href="{% url 'sitio:registrarse' %}">Registrarse</a>
                    {% endif %}                     
                </div>   
                <h1><img src="{% static 'Logo.png' %}" width="250" height="40" top="100"></h1>                  
            </header>
          
            <!-- Barra de menú -->   
            <nav class="navbar navbar-expand-lg" style="background-color: #e8f1fa;">
                <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'sitio:index' %}">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">Categorías</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            {% for categoria in lista_categorias %}
                                <li><a class="dropdown-item" href="{% url 'sitio:filtro_categorias' categoria.id%}">{{ categoria }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'sitio:acerca_de' %}">Acerca de...</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="mailto:jaguaretekaa@test.com.ar">Contacto</a>    <a href=></a>
                    </li>
                    {% if user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'sitio:producto_alta'%}" tabindex="-1">Nuevo Producto</a>
                    </li>
                    {% endif %}
                    </ul>
                    <form class="d-flex" action="{% url 'sitio:filtro_busqueda'%}" method="get">
                        <input class="form-control me-2" type="search" placeholder="Buscar producto" aria-label="Search" name="buscador" value="{{ request.GET.buscador }}">
                        <button class="btn btn-outline-success" type="submit">Buscar</button>
                    </form>
                </div>
                </div>
            </nav>      

            {% block content %}
            {% endblock %}
            <footer>
                <div id="pie-pag">
                    <h7>Copyright © 2021 JAGUARETE KAA S.A.</h7><br>
                    <h7>Desarrollado por Mauro Favero</h7>
                </div>                
            </footer>    
        </div>
 


    </body>
</html>

sitio/templates/blog/producto_edicion.html
{% extends "blog/layout.html" %}
{% load crispy_forms_tags %}
{% block content %}
<br>
<h4>Modificar producto</h4>
<a class="btn btn-primary btn-sm" href="{% url 'sitio:producto_eliminacion' producto.id %}" role="button"> Eliminar </a>

<br>
<form enctype="multipart/form-data" action="{% url 'sitio:producto_edicion' producto.id %}" method="post" >
    {% csrf_token %}
    {{ form | crispy }} 
    <br>
    <div class="col-auto">
        <input type="submit" class="btn btn-primary" value="Guardar">
    </div>
</form>

<br>
{% endblock %}

sitio/templates/blog/producto_nuevo.html
{% extends "blog/layout.html" %}
{% load crispy_forms_tags %}
{% block content %}
<br>
<h4>Crear Producto</h4>
<form enctype="multipart/form-data" action="{% url 'sitio:producto_alta' %}" method="post" >
    {% csrf_token %}
    {{ form | crispy }} 
    <br>
    <div class="col-auto">
        <input type="submit" class="btn btn-primary" value="Guardar">
    </div>
</form>

<br>
{% endblock %}

sitio/templates/blog/producto_vista.html
{% extends "blog/layout.html" %}
{% block content %}
<br>
<h4>Producto: {{ producto.titulo }}</h4>

<div class="container">
    <div class="row">
      <div class="col order-last">           
            <br>      
            <h5>{{ producto.categoria }}</h5>       
            <p id="contenido">Descripción: {{ producto.descripcion |safe }}</p>

            <div class="container">
                <div class="row">
                  <div class="col order-last">
                    {% if user.is_authenticated and not user.is_staff %}
                    <a class="btn btn-outline-primary" href="{% url 'sitio:carrito_agregar' producto.id %}" role="button"> Agregar al carrito </a>   
                    {% endif %}
                  </div>
                  <div class="col order-first">
                    <h6>Precio:  $ {{ producto.precio }}</h6> 
                  </div>
                </div>
              </div>
            <br>       
      </div>
      <div class="col order-first">
            <br>
            <p><img src="{{ media_url  }}{{ producto.imagen.url }}" alt="{{ producto.imagen.name }}"  width="350" height="300" /></p>
            <br><br>  
      </div>
    </div>
  </div>


{% endblock %}